<a href="https://colab.research.google.com/github/Grashch/Tasks-from-leetcode/blob/main/1193_Monthly_Transactions_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd

In [13]:
# Pandas Schema
data = [[121, 'US', 'approved', 1000, '2018-12-18'], [122, 'US', 'declined', 2000, '2018-12-19'], [123, 'US', 'approved', 2000, '2019-01-01'], [124, 'DE', 'approved', 2000, '2019-01-07']]
transactions = pd.DataFrame(data, columns=['id', 'country', 'state', 'amount', 'trans_date']).astype({'id':'Int64', 'country':'object', 'state':'object', 'amount':'Int64', 'trans_date':'datetime64[ns]'})

In [14]:
transactions

    id country     state  amount trans_date
0  121      US  approved    1000 2018-12-18
1  122      US  declined    2000 2018-12-19
2  123      US  approved    2000 2019-01-01
3  124      DE  approved    2000 2019-01-07

In [15]:
transactions['trans_date'] = pd.to_datetime(transactions['trans_date'])
transactions['month'] = transactions['trans_date'].dt.strftime('%Y-%m')
transactions['month']

0    2018-12
1    2018-12
2    2019-01
3    2019-01
Name: month, dtype: object

In [20]:
result = transactions.groupby(['month', 'country']).agg(
    trans_count = ('state', 'count'),
    approved_count = ('state', lambda x: (x == 'approved').sum()),
    trans_total_amount = ('amount', 'sum'),
    approved_total_amount = ('amount', lambda x: x[transactions.loc[x.index, 'state'] == 'approved'].sum())
).reset_index()
result

,month,country,trans_count,approved_count,trans_total_amount,approved_total_amount
0,2018-12,US,2,1,3000,1000
1,2019-01,DE,1,1,2000,2000
2,2019-01,US,1,1,2000,2000